spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false # Default true 이므로 신경써서 false 처리해주어야함.
  sql:
    init:
      mode: always
  security:
    user:
      name: user
      password: ENC(cyxzAxs18G4Jphf0bYK5n/bfveMNu4h8giZaLSxb6eUrHIpa2AgDxVfepYQxDyCh)

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
