spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false # Default true 이므로 신경써서 false 처리해주어야함.
  sql:
    init:
      mode: always
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG

cron:
  message: "0 * * * * *" # 매 분 0초에
