spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000
#    username:
#    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true
    open-in-view: false # Default true 이므로 신경써서 false 처리해주어야함.
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always
  security:
    user:
      name: user
      password: ENC(cyxzAxs18G4Jphf0bYK5n/bfveMNu4h8giZaLSxb6eUrHIpa2AgDxVfepYQxDyCh)

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.transaction: DEBUG
