spring:
  application:
    name: webmvc-jpa
  datasource:
    url: jdbc:h2:mem:jpa
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
        # password123123
        web-admin-password: 929cacf55b5890df49fe0b8dc41c31ce609aad513be28ba19cbd997c56968f0e79ffc6ef74ed36dea08556f64002a25cd9aaab3715e4d3bc66fa133b89efd62a
  security:
    user:
      name: user
      password: password

logging:
  level:
    web: debug
    sql: debug
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

